version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    privileged: true
    ports:
      - 30000:8080
    container_name: jenkins
    volumes:
      - ./jenkins_compose/jenkins_configuration:/var/jenkins_home
      - ./var/run/docker.sock:/var/run/docker.sock
      - ./var/jenkins_home/secrets:/var/jenkins_home/secrets
